openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-refdata-courthearing-courthouses/0.0.0

info:
  title: Common Platform API Refdata Court Hearing Court Houses
  description: Reference Data API providing information on Court Houses associated with a Court Hearing
  version: 0.0.0
  contact:
    email: no-reply@hmcts.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

paths:
  /courthouses/{court_id}:
    get:
      description: Retrieve details of a court house by court_id
      operationId: getCourthouseByCourtId
      tags:
        - court house
      parameters:
        - in: path
          name: court_id
          required: true
          description: Unique reference number for the court house
          schema:
            type: string

      responses:
        '200':
          description: court details found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourtHouse"
        '400':
          description: bad input parameter

components:
  schemas:
    CourtHouse:
      description: The court house that owns the court rooms
      type: object
      properties:
        courtHouseType:
          description: Specifies the type of court
          type: string
          enum:
            - crown
            - magistrate
          example: "crown"
        courtHouseCode:
          description: Links to the court that is responsible for the courtrooms
          type: string
          example: "LND001"
        courtHouseName:
          description: Name of the court house
          type: string
          example: "Central London County Court"
        courtHouseDescription:
          description: Description of the court
          type: string
          example: "Main Crown Court in London handling major cases"
        courtRoom:
          type: array
          items:
            description: The court room that owns the court rooms
            type: object
            properties:
              courtRoomNumber:
                description: Court room number in court
                type: integer
                example: "1"
              courtRoomId:
                description: Ref data id (EPIMS or OU Court id)
                type: integer
                example: "101"
              courtRoomName:
                description: Name for the court room
                type: string
                example: "Courtroom A"
              venueContact:
                description: Contact details for the venue
                type: object
                properties:
                  venueTelephone:
                    description: Telephone number for the venue
                    title: Venue Telephone
                    type: string
                    default: ''
                    example: '01772 844700'
                    pattern: "^.*$"
                  venueEmail:
                    description: Email for the venue
                    title: Venue Email
                    type: string
                    default: ''
                    example: 'court1@moj.gov.uk'
                    pattern: "^.*$"
                  primaryContactName:
                    description: Name for contact of court
                    title: Primary Contact Name
                    type: string
                    default: ''
                    example: 'Name'
                    pattern: "^.*$"
                  venueSupport:
                    description: National contact number for MOJ Courts and Venues
                    title: Venue Support
                    type: string
                    default: ''
                    example: '0330 566 5561'
                    pattern: "^.*$"
                additionalProperties: false
              address:
                description: Courthouse address
                type: object
                properties:
                  address1:
                    description: Address Line 1
                    type: string
                    default: ''
                    example: 'Thomas More Building'
                  address2:
                    description: Address Line 2
                    type: string
                    default: ''
                    example: 'Royal Courts of Justice'
                  address3:
                    description: Address Line 3
                    type: string
                    default: ''
                    example: 'Strand'
                  address4:
                    description: Address Line 4
                    type: string
                    default: ''
                    example: 'London'
                  postalCode:
                    description: UK postcode
                    type: string
                    default: ''
                    example: 'WC2A 2LL'
                    pattern: "^(([gG][iI][rR] {0,}0[aA]{2})|(([aA][sS][cC][nN]|[sS][tT][hH][lL]|[tT][dD][cC][uU]|[bB][bB][nN][dD]|[bB][iI][qQ][qQ]|[fF][iI][qQ][qQ]|[pP][cC][rR][nN]|[sS][iI][qQ][qQ]|[iT][kK][cC][aA]) {0,}1[zZ]{2})|((([a-pr-uwyzA-PR-UWYZ][a-hk-yxA-HK-XY]?[0-9][0-9]?)|(([a-pr-uwyzA-PR-UWYZ][0-9][a-hjkstuwA-HJKSTUW])|([a-pr-uwyzA-PR-UWYZ][a-hk-yA-HK-Y][0-9][abehmnprv-yABEHMNPRV-Y]))) {0,}[0-9][abd-hjlnp-uw-zABD-HJLNP-UW-Z]{2}))$"
                  country:
                    description: United Kingdom
                    type: string
                    default: ''
                    example: 'UK'
                additionalProperties: false
