openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-refdata-courthearing-courthouses/0.0.0

info:
  description: Reference Data API providing information on Court Houses associated with a Court Hearing
  version: 0.0.0
  title: API CP Refdata Court Hearing Court Houses
  contact:
    email: no-reply@hmcts.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

paths:
  /courthouses/{court_id}:
    get:
      description: Retrieve details of a court house by court_id
      operationId: getCourthouseByCourtId
      tags:
        - court house
      parameters:

        - in: path
          name: court_id
          required: true
          description: Unique reference number for the court house
          schema:
            type: string

      responses:
        '200':
          description:  court details found

          content:
            application/json:
              schema:
                  $ref: "schema/courtHouses.json"
              example:
                courtHouse:
                  courtHouseType: crown
                  courtHouseCode: CH123
                  courtHouseName: Central Crown Court
                  courtHouseDescription: The main court for crown-level trials in the region.
                  courtRoom:
                    - courtRoomNumber: 1
                      courtRoomId: 1001
                      courtRoomName: Courtroom A
                      venueContact:
                        venueTelephone: "01772 844700"
                        venueEmail: "court1@moj.gov.uk"
                        primaryContactName: "John Doe"
                        venueSupport: "0330 566 5561"


        '400':
          description: bad input parameter
