openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-refdata-courthearing-courthouses/0.0.1

info:
  description: Court House API
  version: 0.0.1
  title: api-cp-refdata-courthearing-courthouses
  contact:
    email: api@hmcts.com
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/hmcts/api-cp-refdata-courthearing-courthouses/refs/heads/master/LICENSE'

paths:
  /courthouses/{court_id}:
    get:
  
      parameters:
      
        - in: path
          name: court_id
          required: true
          description: Unique reference number for the court house
          schema:
            type: string
       
      responses:
        '200':
          description:  court details found
          
          content:
            application/json:
              schema:
                  $ref: "courtHouses.schema.json"
              example:
                courtHouse:
                  courtHouseType: crown
                  courtHouseCode: CH123
                  courtHouseName: Central Crown Court
                  courtHouseDescription: The main court for crown-level trials in the region.
                  courtRoom:
                    - courtRoomNumber: 1
                      courtRoomId: 1001
                      courtRoomName: Courtroom A
                      venueContact:
                        venueTelephone: "01772 844700"
                        venueEmail: "court1@moj.gov.uk"
                        primaryContactName: "John Doe"
                        venueSupport: "0330 566 5561"
    
      
        '400':
          description: bad input parameter
