openapi: 3.0.0
servers:
  
  - description: SwaggerHub API Auto Mocking court-schedule_api
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/court-schedule_api/0.0.1

info:
  description: api-cp-crime-schedulingandlisting-courtschedule
  version: 0.0.1
  title: api-cp-crime-schedulingandlisting-courtschedule
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /case/{case_urn}/courtschedule:
    get:
  
      parameters:
      
        - in: path
          name: case_urn
          required: true
          description: Unique reference number for the case
          schema:
            type: string
       
      responses:
        '200':
          description:  case found
          
          content:
            application/json:
              schema:
                  $ref: "https://raw.githubusercontent.com/hmcts/api-cp-crime-schedulingandlisting-courtschedule/master/openapi/v0.0.1/courtSchedule.schema.json"
              example:
                courtSchedule:
                  - hearings:
                      - hearingId: HRG-123456
                        hearingType: Trial
                        hearingDescription: Sentencing for theft case
                        listNote: Requires interpreter
                        courtSittings:
                          - sittingStart: 2025-03-25T09:00:00Z
                            sittingEnd: 2025-03-25T12:00:00Z
                            judiciaryid: 123e4567-e89b-12d3-a456-426614174000
                            courtHouse: 223e4567-e89b-12d3-a456-426614174111
      
        '400':
          description: bad input parameter